import matplotlib.pyplot as plt
import matplotlib.animation as animation
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
import argparse
import sys
import os


def parse_arguments():
    parser = argparse.ArgumentParser(
        description="Visualize 3D N-Body Galaxy Simulation from CSV data."
    )

    parser.add_argument(
        "-i",
        "--input",
        type=str,
        default="output.csv",
        help="Path to the input CSV file generated by the CUDA program (default: output.csv)",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=str,
        default="galaxy_simulation.html",
        help="Path to the output HTML file (default: galaxy_simulation.html)",
    )

    parser.add_argument(
        "--fps",
        type=int,
        default=30,
        help="Frames Per Second for the animation (default: 30)",
    )
    parser.add_argument(
        "--limit",
        type=float,
        default=150.0,
        help="Axis limits for the 3D plot box (default: 150.0)",
    )
    parser.add_argument(
        "--size", type=float, default=2.0, help="Size of the particles (default: 2.0)"
    )
    parser.add_argument(
        "--alpha",
        type=float,
        default=0.6,
        help="Transparency of particles 0.0 to 1.0 (default: 0.6)",
    )

    return parser.parse_args()


def parse_nbody_data(filename):
    """
    The data is shaped like a csv, but missing crucial elements, like the header which is useless in our case
    """

    frames = []

    if not os.path.exists(filename):
        print(f"Error: Input file '{filename}' not found.")
        sys.exit(1)

    print(f"Reading data from {filename}...")
    try:
        with open(filename, "r") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue

                parts = line.split(",")

                if len(parts) % 3 != 0 or len(parts) == 0:
                    continue

                try:
                    data = np.array([float(x) for x in parts])
                    n_particles = len(data) // 3
                    frame_data = data.reshape((n_particles, 3))
                    frames.append(frame_data)
                except ValueError:
                    continue

    except Exception as e:
        print(f"Error reading file: {e}")
        sys.exit(1)

    return frames


def create_animation(frames, args):
    plt.style.use("dark_background")
    fig = plt.figure(figsize=(10, 8))
    ax = fig.add_subplot(111, projection="3d")

    # removing grid to make a "space" vibe look
    ax.grid(False)
    ax.xaxis.pane.fill = False
    ax.yaxis.pane.fill = False
    ax.zaxis.pane.fill = False

    ax.xaxis._axinfo["grid"]["color"] = (1, 1, 1, 0.1)
    ax.yaxis._axinfo["grid"]["color"] = (1, 1, 1, 0.1)
    ax.zaxis._axinfo["grid"]["color"] = (1, 1, 1, 0.1)

    first_frame = frames[0]
    scatter = ax.scatter(
        first_frame[:, 0],
        first_frame[:, 1],
        first_frame[:, 2],
        c="cyan",  # color of stars
        s=args.size,  # size of stars
        alpha=args.alpha,
        edgecolors="none",
    )

    limit = args.limit
    ax.set_xlim(-limit, limit)
    ax.set_ylim(-limit, limit)
    ax.set_zlim(-limit, limit)
    ax.set_title(f"N-Body Simulation ({len(frames)} frames)")

    def update(frame_idx):
        current_frame = frames[frame_idx]

        scatter._offsets3d = (
            current_frame[:, 0],
            current_frame[:, 1],
            current_frame[:, 2],
        )

        # this rotate the animation, making things clearer
        ax.view_init(elev=15, azim=frame_idx * 0.2)

        return (scatter,)

    print(f"Generating animation with {len(frames)} frames at {args.fps} FPS...")

    anim = animation.FuncAnimation(
        fig, update, frames=len(frames), interval=1000 / args.fps, blit=False
    )

    return anim


def main():
    args = parse_arguments()

    frames = parse_nbody_data(args.input)

    if not frames:
        print("Error: No valid simulation steps found in the input file.")
        sys.exit(1)

    print(
        f"Successfully loaded {len(frames)} frames. Particles per frame: {len(frames[0])}"
    )

    print(f"Saving HTML to {args.output} (this might take a moment)...")
    anim = create_animation(frames, args)

    if False: # temp for readme
        anim.save("galaxy.gif", writer="pillow", fps=args.fps)
    anim.to_jshtml()

    with open(args.output, "w") as f:
        f.write(anim.to_jshtml())

    print(f"Done! Open '{args.output}' in your web browser.")


if __name__ == "__main__":
    main()
